### PR TITLE
Allow timeout on handshake handler

### PR DESCRIPTION
**Pull request by kc7bfi**
Allow a timeout on the sync() call. This is to prevent the call from hanging and never returning.

### CODE REVIEW

**Comment by kc7bfi** [comment]
Any idea when this fix may be integrated into the main code?

**Comment by kc7bfi** [comment]
I'm not sure how to split multiple commits into different pull requests. However, I've added code to name the async threads used in the WebSocket service class.

**Comment by kc7bfi** [comment]
Any idea if an when this pull request can be added to the main development branch?

**Comment by kc7bfi** [comment]
Found some more places where the sync() call can hang and never return

**Comment by nordri** [comment]
Hi @kc7bfi 

The new Kurento team is now very small (after Twilio adquisition of most of developers) and we are very busy with other issues. Sorry.

**Comment by j1elo** [comment]
Sorry for the time it took, and thanks for the friendly reminder :-)
This gets in time to ship with release 6.11

**Comment by j1elo** [comment]
Hi, after some afterwards testing and discussion, we took the decision to have @pabloFuente rolling this change back (done in Kurento/kurento-java@1827a7c680ce84a4bfed7042334fc276a0b077f2), because it introduces a fundamental change in how connections to the media server WS API were managed, which is in essence a breaking change in functionality.

With sync mode, applications know when KMS is not responding or not even started, with an immediate feedback due to failed connection. Changing to future-based async means that this case would need to wait for the timeout to happen, before getting a connection failure. This breaks some of our tests, and it will also break applications that expect the old behavior. We cannot break applications.

On the other hand, the sync code does indeed have the issue of sometimes hanging indefinitely while trying a reconnect. More info: [Connection to KMS hangs](https://groups.google.com/d/topic/kurento/DtIKvp-J764/discussion). This should be treated as a bug in itself, and seek proper fixing of the issue, instead of completely changing the connection paradigm from synchronous to asynchronous.

**Comment by mitch2na** [comment]
@j1elo Added a new PR that is backwards compatible https://github.com/Kurento/kurento-java/pull/18

**Pull request merged**
