### PR TITLE
EventListener is now @FunctionalInterface

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
Unfortunately I can't check what were the errors :( (not enough rights)
Local build was successful ...

**Comment by solomax** [comment]
Ping

**Comment by micaelgallego** [comment]
I'm sorry but right now KurentoClient is Java 7 compatible. We plan to update to Java 8 in 7.0.0 version.

We will accept it then.

**Comment by solomax** [comment]
Thanks for the answer @micaelgallego :)
Any ETA for 7.0.0?

**Comment by solomax** [comment]
@micaelgallego Thanks a million, I totally forgot about it :(

**Comment by micaelgallego** [comment]
I suppose that

**Pull request closed without merging**
